--- #YAML:1.0
name:                MooseX-Types-URI
version:             0.01
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Moose:                         0.50
    MooseX::Types:                 0
    MooseX::Types::Path::Class:    0
    namespace::clean:              0.08
    Test::use::ok:                 0
    URI:                           0
    URI::FromHash:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
