--- #YAML:1.0
name:               MooseX-Types-URI
version:            0.02
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:                0.50
    MooseX::Types:        0
    MooseX::Types::Path::Class:  0
    namespace::clean:     0.08
    Test::use::ok:        0
    URI:                  0
    URI::FromHash:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
